[2019-07-17 15:36:33,094][INFO] - =========脚本启动=========
[2019-07-17 15:36:33,199][ERROR] - No operations allowed after connection closed.
java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:1094)
	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:1084)
	at util.DataBaseSource.createReportTable(DataBaseSource.java:125)
	at common.ElementAction.action(ElementAction.java:81)
	at Start.main(Start.java:8)
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:1263)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:575)
	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java)
	... 4 more
[2019-07-17 15:36:33,202][INFO] - 开始执行脚本：1.xls
[2019-07-17 15:36:33,809][INFO] - 启动chrome浏览器
[2019-07-17 15:36:36,992][INFO] - 1步开始
[2019-07-17 15:36:37,695][INFO] - 2步开始
[2019-07-17 15:37:07,839][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 15:37:07,932][ERROR] - 第2步发生异常
[2019-07-17 15:37:07,932][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:174)
	at Start.main(Start.java:8)
[2019-07-17 15:37:07,933][INFO] - 执行报错，关闭浏览器
[2019-07-17 15:37:07,935][ERROR] - No operations allowed after connection closed.
java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:1094)
	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:1084)
	at util.DataBaseSource.insertDetail(DataBaseSource.java:82)
	at common.ElementAction.action(ElementAction.java:525)
	at Start.main(Start.java:8)
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:1263)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:575)
	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java)
	... 4 more
[2019-07-17 15:37:07,936][INFO] - 1.xls执行完成
[2019-07-17 15:37:07,943][INFO] - 启动chrome浏览器
[2019-07-17 15:37:11,195][INFO] - 1步开始
[2019-07-17 15:37:11,891][INFO] - 2步开始
[2019-07-17 15:37:12,557][INFO] - 3步开始
[2019-07-17 15:37:17,408][INFO] - 4步开始
[2019-07-17 15:37:18,231][INFO] - 5步开始
[2019-07-17 15:37:19,003][INFO] - 6步开始
[2019-07-17 15:37:21,474][INFO] - 7步开始
[2019-07-17 15:37:22,083][INFO] - 8步开始
[2019-07-17 15:37:22,864][INFO] - 9步开始
[2019-07-17 15:37:23,423][INFO] - 94步开始
[2019-07-17 15:37:24,771][INFO] - 95步开始
[2019-07-17 15:37:25,409][INFO] - 96步开始
[2019-07-17 15:37:26,017][INFO] - 97步开始
[2019-07-17 15:37:56,374][ERROR] - 元素(ID)'thumbFIleUpload'找不到
[2019-07-17 15:37:56,535][ERROR] - 第97步发生异常
[2019-07-17 15:37:56,535][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:263)
	at Start.main(Start.java:8)
[2019-07-17 15:37:56,536][INFO] - 执行报错，关闭浏览器
[2019-07-17 15:37:56,537][ERROR] - No operations allowed after connection closed.
java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:1094)
	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:1084)
	at util.DataBaseSource.insertDetail(DataBaseSource.java:82)
	at common.ElementAction.action(ElementAction.java:525)
	at Start.main(Start.java:8)
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:1263)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:575)
	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java)
	... 4 more
[2019-07-17 15:37:56,538][INFO] - 1.xls执行完成
[2019-07-17 15:37:56,538][INFO] - =========脚本完成=========
[2019-07-17 15:37:56,546][ERROR] - No operations allowed after connection closed.
java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:1094)
	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:1084)
	at util.DataBaseSource.update(DataBaseSource.java:67)
	at common.ElementAction.action(ElementAction.java:533)
	at Start.main(Start.java:8)
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:1263)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:575)
	at com.mysql.cj.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java)
	... 4 more
[2019-07-17 15:41:53,801][INFO] - =========脚本启动=========
[2019-07-17 15:41:54,037][ERROR] - Incorrect table name ''
java.sql.SQLSyntaxErrorException: Incorrect table name ''
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1355)
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2128)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1264)
	at util.DataBaseSource.createReportTable(DataBaseSource.java:126)
	at common.ElementAction.action(ElementAction.java:81)
	at Start.main(Start.java:8)
[2019-07-17 15:41:54,040][INFO] - 开始执行脚本：1.xls
[2019-07-17 15:41:54,419][INFO] - 启动chrome浏览器
[2019-07-17 15:41:57,310][INFO] - 1步开始
[2019-07-17 15:41:58,011][INFO] - 2步开始
[2019-07-17 15:42:43,093][INFO] - =========脚本启动=========
[2019-07-17 15:42:43,511][INFO] - 开始执行脚本：1.xls
[2019-07-17 15:42:43,715][INFO] - 启动chrome浏览器
[2019-07-17 15:42:46,214][INFO] - 1步开始
[2019-07-17 15:42:46,907][INFO] - 2步开始
[2019-07-17 15:43:16,956][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 15:43:17,040][ERROR] - 第2步发生异常
[2019-07-17 15:43:17,041][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:174)
	at Start.main(Start.java:8)
[2019-07-17 15:43:17,044][INFO] - 执行报错，关闭浏览器
[2019-07-17 15:43:17,058][ERROR] - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Sheet1','2019-07-17 15:42:43','2019-07-17 15:43:17','第2步发生异常')' at line 1
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Sheet1','2019-07-17 15:42:43','2019-07-17 15:43:17','第2步发生异常')' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1355)
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2128)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1264)
	at util.DataBaseSource.insertDetail(DataBaseSource.java:83)
	at common.ElementAction.action(ElementAction.java:525)
	at Start.main(Start.java:8)
[2019-07-17 15:43:17,058][INFO] - 1.xls执行完成
[2019-07-17 15:43:17,108][INFO] - 启动chrome浏览器
[2019-07-17 15:43:19,111][INFO] - 1步开始
[2019-07-17 15:43:19,901][INFO] - 2步开始
[2019-07-17 15:43:20,530][INFO] - 3步开始
[2019-07-17 15:43:32,549][INFO] - 4步开始
[2019-07-17 15:43:41,456][INFO] - 5步开始
[2019-07-17 15:43:42,259][INFO] - 6步开始
[2019-07-17 15:43:44,221][INFO] - 7步开始
[2019-07-17 15:43:44,808][INFO] - 8步开始
[2019-07-17 15:43:45,516][INFO] - 9步开始
[2019-07-17 15:43:46,062][INFO] - 94步开始
[2019-07-17 15:43:46,966][INFO] - 95步开始
[2019-07-17 15:43:47,597][INFO] - 96步开始
[2019-07-17 15:43:48,190][INFO] - 97步开始
[2019-07-17 15:43:48,758][INFO] - 98步开始
[2019-07-17 15:43:49,347][INFO] - 99步开始
[2019-07-17 15:43:52,304][INFO] - 截图保存到:/idea/UIAutoTest/pic/snap_1.xls_step99_2019-07-17 15:43:49.png
[2019-07-17 15:43:52,832][INFO] - 100步开始
[2019-07-17 15:43:53,336][INFO] - sleep:500毫秒
[2019-07-17 15:43:53,853][INFO] - 101步开始
[2019-07-17 15:43:54,448][INFO] - end步开始
[2019-07-17 15:43:54,448][INFO] - Sheet2执行完成
[2019-07-17 15:43:54,673][INFO] - 表格:Sheet2完成，关闭浏览器
[2019-07-17 15:43:54,676][ERROR] - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Sheet2','2019-07-17 15:43:17','2019-07-17 15:43:54','PASS')' at line 1
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Sheet2','2019-07-17 15:43:17','2019-07-17 15:43:54','PASS')' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1355)
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2128)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1264)
	at util.DataBaseSource.insertDetail(DataBaseSource.java:83)
	at common.ElementAction.action(ElementAction.java:515)
	at Start.main(Start.java:8)
[2019-07-17 15:43:54,676][INFO] - 1.xls执行完成
[2019-07-17 15:43:54,676][INFO] - =========脚本完成=========
[2019-07-17 15:43:54,678][ERROR] - Table 'datakreport.test_report' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'datakreport.test_report' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1355)
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2128)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1264)
	at util.DataBaseSource.update(DataBaseSource.java:68)
	at common.ElementAction.action(ElementAction.java:533)
	at Start.main(Start.java:8)
[2019-07-17 15:44:51,462][INFO] - =========脚本启动=========
[2019-07-17 15:44:51,914][INFO] - 开始执行脚本：1.xls
[2019-07-17 15:44:52,231][INFO] - 启动chrome浏览器
[2019-07-17 15:44:55,298][INFO] - 1步开始
[2019-07-17 15:44:55,986][INFO] - 2步开始
[2019-07-17 15:45:26,017][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 15:45:26,139][ERROR] - 第2步发生异常
[2019-07-17 15:45:26,141][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:174)
	at Start.main(Start.java:8)
[2019-07-17 15:45:26,144][INFO] - 执行报错，关闭浏览器
[2019-07-17 15:47:49,177][ERROR] - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Sheet1','2019-07-17 15:44:52','2019-07-17 15:45:26','第2步发生异常')' at line 1
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Sheet1','2019-07-17 15:44:52','2019-07-17 15:45:26','第2步发生异常')' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1355)
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2128)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1264)
	at util.DataBaseSource.insertDetail(DataBaseSource.java:83)
	at common.ElementAction.action(ElementAction.java:525)
	at Start.main(Start.java:8)
[2019-07-17 15:47:49,180][INFO] - 1.xls执行完成
[2019-07-17 15:47:49,194][INFO] - 启动chrome浏览器
[2019-07-17 15:47:52,562][INFO] - =========脚本启动=========
[2019-07-17 15:47:53,050][INFO] - 开始执行脚本：1.xls
[2019-07-17 15:47:53,316][INFO] - 启动chrome浏览器
[2019-07-17 15:47:55,819][INFO] - 1步开始
[2019-07-17 15:47:56,493][INFO] - 2步开始
[2019-07-17 15:48:26,995][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 15:48:27,081][ERROR] - 第2步发生异常
[2019-07-17 15:48:27,081][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:174)
	at Start.main(Start.java:8)
[2019-07-17 15:48:27,084][INFO] - 执行报错，关闭浏览器
[2019-07-17 15:48:27,119][INFO] - 1.xls执行完成
[2019-07-17 15:48:27,125][INFO] - 启动chrome浏览器
[2019-07-17 15:48:29,268][INFO] - 1步开始
[2019-07-17 15:48:29,983][INFO] - 2步开始
[2019-07-17 15:48:30,650][INFO] - 3步开始
[2019-07-17 15:48:35,333][INFO] - 4步开始
[2019-07-17 15:48:36,412][INFO] - 5步开始
[2019-07-17 15:48:37,210][INFO] - 6步开始
[2019-07-17 15:48:39,542][INFO] - 7步开始
[2019-07-17 15:48:40,182][INFO] - 8步开始
[2019-07-17 15:48:40,980][INFO] - 9步开始
[2019-07-17 15:48:41,561][INFO] - 94步开始
[2019-07-17 15:48:42,912][INFO] - 95步开始
[2019-07-17 15:48:43,548][INFO] - 96步开始
[2019-07-17 15:48:44,139][INFO] - 97步开始
[2019-07-17 15:48:44,716][INFO] - 98步开始
[2019-07-17 15:48:45,306][INFO] - 99步开始
[2019-07-17 15:48:48,141][INFO] - 截图保存到:/idea/UIAutoTest/pic/snap_1.xls_step99_2019-07-17 15:48:45.png
[2019-07-17 15:48:48,678][INFO] - 100步开始
[2019-07-17 15:48:49,178][INFO] - sleep:500毫秒
[2019-07-17 15:48:49,697][INFO] - 101步开始
[2019-07-17 15:48:50,301][INFO] - end步开始
[2019-07-17 15:48:50,301][INFO] - Sheet2执行完成
[2019-07-17 15:48:50,537][INFO] - 表格:Sheet2完成，关闭浏览器
[2019-07-17 15:48:50,593][INFO] - 1.xls执行完成
[2019-07-17 15:48:50,593][INFO] - =========脚本完成=========
[2019-07-17 15:48:50,622][ERROR] - Table 'datakreport.test_report' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'datakreport.test_report' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1355)
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2128)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1264)
	at util.DataBaseSource.update(DataBaseSource.java:68)
	at common.ElementAction.action(ElementAction.java:533)
	at Start.main(Start.java:8)
[2019-07-17 15:57:50,653][INFO] - =========脚本启动=========
[2019-07-17 15:57:51,534][INFO] - 开始执行脚本：1.xls
[2019-07-17 15:57:51,787][INFO] - 启动chrome浏览器
[2019-07-17 15:57:54,636][INFO] - 1步开始
[2019-07-17 15:57:55,319][INFO] - 2步开始
[2019-07-17 15:58:25,806][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 15:58:25,947][ERROR] - 第2步发生异常
[2019-07-17 15:58:25,948][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:172)
	at Start.main(Start.java:8)
[2019-07-17 15:58:25,954][INFO] - 执行报错，关闭浏览器
[2019-07-17 15:58:26,014][INFO] - 1.xls执行完成
[2019-07-17 15:58:26,021][INFO] - 启动chrome浏览器
[2019-07-17 15:58:28,417][INFO] - 1步开始
[2019-07-17 15:58:29,120][INFO] - 2步开始
[2019-07-17 15:58:29,774][INFO] - 3步开始
[2019-07-17 15:58:31,352][INFO] - 4步开始
[2019-07-17 15:58:35,670][INFO] - 5步开始
[2019-07-17 15:58:36,508][INFO] - 6步开始
[2019-07-17 15:58:39,073][INFO] - 7步开始
[2019-07-17 15:58:39,681][INFO] - 8步开始
[2019-07-17 15:58:40,460][INFO] - 9步开始
[2019-07-17 15:58:41,032][INFO] - 94步开始
[2019-07-17 15:58:42,483][INFO] - 95步开始
[2019-07-17 15:58:43,118][INFO] - 96步开始
[2019-07-17 15:58:43,712][INFO] - 97步开始
[2019-07-17 15:58:44,287][INFO] - 98步开始
[2019-07-17 15:58:44,888][INFO] - 99步开始
[2019-07-17 15:58:47,686][INFO] - 截图保存到:/idea/UIAutoTest/pic/snap_1.xls_step99_2019-07-17 15:58:44.png
[2019-07-17 15:58:48,217][INFO] - 100步开始
[2019-07-17 15:58:48,723][INFO] - sleep:500毫秒
[2019-07-17 15:58:49,234][INFO] - 101步开始
[2019-07-17 15:58:49,843][INFO] - end步开始
[2019-07-17 15:58:49,844][INFO] - Sheet2执行完成
[2019-07-17 15:58:50,082][INFO] - 表格:Sheet2完成，关闭浏览器
[2019-07-17 15:58:50,156][INFO] - 1.xls执行完成
[2019-07-17 15:58:50,156][INFO] - =========脚本完成=========
[2019-07-17 17:11:27,678][INFO] - =========脚本启动=========
[2019-07-17 17:11:28,048][ERROR] - Access denied for user '/Users/linjunjie/Downloads/bc4f054efc3cb80ad7030'@'172.16.0.75' (using password: YES)
java.sql.SQLException: Access denied for user '/Users/linjunjie/Downloads/bc4f054efc3cb80ad7030'@'172.16.0.75' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at util.DataBaseSource.getConn(DataBaseSource.java:34)
	at util.DataBaseSource.getReportTableName(DataBaseSource.java:115)
	at common.ElementAction.action(ElementAction.java:78)
	at Start.main(Start.java:8)
[2019-07-17 17:12:17,099][INFO] - =========脚本启动=========
[2019-07-17 17:12:17,530][ERROR] - Access denied for user '/Users/linjunjie/Downloads/bc4f054efc3cb80ad7030'@'172.16.0.75' (using password: YES)
java.sql.SQLException: Access denied for user '/Users/linjunjie/Downloads/bc4f054efc3cb80ad7030'@'172.16.0.75' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at util.DataBaseSource.getConn(DataBaseSource.java:34)
	at util.DataBaseSource.getReportTableName(DataBaseSource.java:115)
	at common.ElementAction.action(ElementAction.java:78)
	at Start.main(Start.java:8)
[2019-07-17 17:12:52,525][INFO] - =========脚本启动=========
[2019-07-17 17:14:01,295][INFO] - =========脚本启动=========
[2019-07-17 17:14:01,607][ERROR] - Access denied for user '/Users/linjunjie/Downloads/bc4f054efc3cb80ad7030'@'172.16.0.75' (using password: YES)
java.sql.SQLException: Access denied for user '/Users/linjunjie/Downloads/bc4f054efc3cb80ad7030'@'172.16.0.75' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at util.DataBaseSource.getConn(DataBaseSource.java:34)
	at util.DataBaseSource.getReportTableName(DataBaseSource.java:115)
	at common.ElementAction.action(ElementAction.java:78)
	at Start.main(Start.java:8)
[2019-07-17 17:14:35,650][INFO] - =========脚本启动=========
[2019-07-17 17:14:37,192][INFO] - 开始执行脚本：1.xls
[2019-07-17 17:14:37,472][INFO] - 启动chrome浏览器
[2019-07-17 17:14:40,333][INFO] - 1步开始
[2019-07-17 17:14:41,014][INFO] - 2步开始
[2019-07-17 17:15:11,034][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 17:15:11,141][ERROR] - 第2步发生异常
[2019-07-17 17:15:11,141][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:171)
	at Start.main(Start.java:8)
[2019-07-17 17:15:11,144][INFO] - 执行报错，关闭浏览器
[2019-07-17 17:15:11,268][INFO] - 1.xls执行完成
[2019-07-17 17:15:11,276][INFO] - 启动chrome浏览器
[2019-07-17 17:15:13,627][INFO] - 1步开始
[2019-07-17 17:15:14,304][INFO] - 2步开始
[2019-07-17 17:15:14,960][INFO] - 3步开始
[2019-07-17 17:15:16,421][INFO] - 4步开始
[2019-07-17 17:15:20,837][INFO] - 5步开始
[2019-07-17 17:15:21,592][INFO] - 6步开始
[2019-07-17 17:15:24,715][INFO] - 7步开始
[2019-07-17 17:15:25,308][INFO] - 8步开始
[2019-07-17 17:15:26,013][INFO] - 9步开始
[2019-07-17 17:15:26,556][INFO] - 94步开始
[2019-07-17 17:15:27,795][INFO] - 95步开始
[2019-07-17 17:15:28,436][INFO] - 96步开始
[2019-07-17 17:15:29,031][INFO] - 97步开始
[2019-07-17 17:15:29,597][INFO] - 98步开始
[2019-07-17 17:15:30,192][INFO] - 99步开始
[2019-07-17 17:15:33,551][INFO] - 截图保存到:/idea/UIAutoTest/pic/snap_1.xls_step99_2019-07-17 17:15:30.png
[2019-07-17 17:15:34,077][INFO] - 100步开始
[2019-07-17 17:15:34,587][INFO] - sleep:500毫秒
[2019-07-17 17:15:35,101][INFO] - 101步开始
[2019-07-17 17:15:35,711][INFO] - end步开始
[2019-07-17 17:15:35,711][INFO] - Sheet2执行完成
[2019-07-17 17:15:35,951][INFO] - 表格:Sheet2完成，关闭浏览器
[2019-07-17 17:15:36,100][INFO] - 1.xls执行完成
[2019-07-17 17:15:36,101][INFO] - =========脚本完成=========
[2019-07-17 17:21:10,405][INFO] - =========脚本启动=========
[2019-07-17 17:21:11,937][INFO] - 开始执行脚本：1.xls
[2019-07-17 17:21:12,116][INFO] - 启动chrome浏览器
[2019-07-17 17:21:14,525][INFO] - 1步开始
[2019-07-17 17:21:15,201][INFO] - 2步开始
[2019-07-17 17:21:45,692][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 17:21:45,787][ERROR] - 第2步发生异常
[2019-07-17 17:21:45,789][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:171)
	at Start.main(Start.java:8)
[2019-07-17 17:21:45,791][INFO] - 执行报错，关闭浏览器
[2019-07-17 17:21:45,882][INFO] - 1.xls执行完成
[2019-07-17 17:21:45,886][INFO] - 启动chrome浏览器
[2019-07-17 17:21:48,266][INFO] - 1步开始
[2019-07-17 17:21:48,970][INFO] - 2步开始
[2019-07-17 17:21:49,644][INFO] - 3步开始
[2019-07-17 17:21:50,959][INFO] - 4步开始
[2019-07-17 17:21:55,830][INFO] - 5步开始
[2019-07-17 17:21:56,587][INFO] - 6步开始
[2019-07-17 17:21:58,941][INFO] - 7步开始
[2019-07-17 17:21:59,545][INFO] - 8步开始
[2019-07-17 17:22:00,275][INFO] - 9步开始
[2019-07-17 17:22:00,841][INFO] - 94步开始
[2019-07-17 17:22:02,263][INFO] - 95步开始
[2019-07-17 17:22:02,972][INFO] - 96步开始
[2019-07-17 17:22:04,347][INFO] - 97步开始
[2019-07-17 17:22:04,946][INFO] - 98步开始
[2019-07-17 17:22:05,596][INFO] - 99步开始
[2019-07-17 17:22:08,689][INFO] - 截图保存到:/idea/UIAutoTest/pic/snap_1.xls_step99_2019-07-17 17:22:05.png
[2019-07-17 17:22:09,213][INFO] - 100步开始
[2019-07-17 17:22:09,719][INFO] - sleep:500毫秒
[2019-07-17 17:22:10,229][INFO] - 101步开始
[2019-07-17 17:22:10,856][INFO] - end步开始
[2019-07-17 17:22:10,856][INFO] - Sheet2执行完成
[2019-07-17 17:22:11,027][INFO] - 表格:Sheet2完成，关闭浏览器
[2019-07-17 17:22:11,136][INFO] - 1.xls执行完成
[2019-07-17 17:22:11,136][INFO] - =========脚本完成=========
[2019-07-17 17:24:10,423][INFO] - =========脚本启动=========
[2019-07-17 17:24:12,063][INFO] - 开始执行脚本：1.xls
[2019-07-17 17:24:12,290][INFO] - 启动chrome浏览器
[2019-07-17 17:24:14,852][INFO] - 1步开始
[2019-07-17 17:24:15,535][INFO] - 2步开始
[2019-07-17 17:24:45,553][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 17:24:45,659][ERROR] - 第2步发生异常
[2019-07-17 17:24:45,661][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:171)
	at Start.main(Start.java:8)
[2019-07-17 17:24:45,667][INFO] - 执行报错，关闭浏览器
[2019-07-17 17:24:45,752][INFO] - 1.xls执行完成
[2019-07-17 17:24:45,756][INFO] - 启动chrome浏览器
[2019-07-17 17:24:47,994][INFO] - 1步开始
[2019-07-17 17:24:48,671][INFO] - 2步开始
[2019-07-17 17:24:49,371][INFO] - 3步开始
[2019-07-17 17:24:50,879][INFO] - 4步开始
[2019-07-17 17:25:08,990][INFO] - =========脚本启动=========
[2019-07-17 17:25:10,910][INFO] - 开始执行脚本：1.xls
[2019-07-17 17:25:11,421][INFO] - 启动chrome浏览器
[2019-07-17 17:25:15,602][INFO] - 1步开始
[2019-07-17 17:25:16,431][INFO] - 2步开始
[2019-07-17 17:25:46,500][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 17:25:46,592][ERROR] - 第2步发生异常
[2019-07-17 17:25:46,593][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:171)
	at Start.main(Start.java:8)
[2019-07-17 17:25:46,596][INFO] - 执行报错，关闭浏览器
[2019-07-17 17:25:46,767][INFO] - 1.xls执行完成
[2019-07-17 17:25:46,772][INFO] - 启动chrome浏览器
[2019-07-17 17:25:49,138][INFO] - 1步开始
[2019-07-17 17:25:49,997][INFO] - 2步开始
[2019-07-17 17:25:50,629][INFO] - 3步开始
[2019-07-17 17:25:56,504][INFO] - 4步开始
[2019-07-17 17:26:00,605][INFO] - 5步开始
[2019-07-17 17:26:01,334][INFO] - 6步开始
[2019-07-17 17:26:03,486][INFO] - 7步开始
[2019-07-17 17:26:04,058][INFO] - 8步开始
[2019-07-17 17:26:04,750][INFO] - 9步开始
[2019-07-17 17:26:05,294][INFO] - 94步开始
[2019-07-17 17:26:06,239][INFO] - 95步开始
[2019-07-17 17:26:06,885][INFO] - 96步开始
[2019-07-17 17:26:07,489][INFO] - 97步开始
[2019-07-17 17:26:08,056][INFO] - 98步开始
[2019-07-17 17:26:08,655][INFO] - 99步开始
[2019-07-17 17:26:11,932][INFO] - 截图保存到:/idea/UIAutoTest/pic/snap_1.xls_step99_2019-07-17 17:26:08.png
[2019-07-17 17:26:12,458][INFO] - 100步开始
[2019-07-17 17:26:12,962][INFO] - sleep:500毫秒
[2019-07-17 17:26:13,472][INFO] - 101步开始
[2019-07-17 17:26:22,192][INFO] - end步开始
[2019-07-17 17:26:22,192][INFO] - Sheet2执行完成
[2019-07-17 17:26:22,430][INFO] - 表格:Sheet2完成，关闭浏览器
[2019-07-17 17:26:22,784][INFO] - 1.xls执行完成
[2019-07-17 17:26:22,784][INFO] - =========脚本完成=========
[2019-07-17 17:58:25,581][INFO] - =========脚本启动=========
[2019-07-17 17:59:14,881][INFO] - =========脚本启动=========
[2019-07-17 17:59:16,649][INFO] - 开始执行脚本：1.xls
[2019-07-17 17:59:16,889][INFO] - 启动chrome浏览器
[2019-07-17 17:59:19,900][INFO] - 1步开始
[2019-07-17 17:59:20,579][INFO] - 2步开始
[2019-07-17 17:59:51,073][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 17:59:51,187][ERROR] - 第2步发生异常
[2019-07-17 17:59:51,188][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:177)
	at Start.main(Start.java:8)
[2019-07-17 17:59:51,191][INFO] - 执行报错，关闭浏览器
[2019-07-17 17:59:51,358][INFO] - 1.xls执行完成
[2019-07-17 17:59:51,367][INFO] - 启动chrome浏览器
[2019-07-17 17:59:53,980][INFO] - 1步开始
[2019-07-17 17:59:54,691][INFO] - 2步开始
[2019-07-17 17:59:55,348][INFO] - 3步开始
[2019-07-17 17:59:57,020][INFO] - 4步开始
[2019-07-17 18:00:01,673][INFO] - 5步开始
[2019-07-17 18:00:02,396][INFO] - 6步开始
[2019-07-17 18:00:04,920][INFO] - 7步开始
[2019-07-17 18:00:05,501][INFO] - 8步开始
[2019-07-17 18:00:06,199][INFO] - 9步开始
[2019-07-17 18:00:06,748][INFO] - 94步开始
[2019-07-17 18:00:07,574][INFO] - 95步开始
[2019-07-17 18:00:08,216][INFO] - 96步开始
[2019-07-17 18:00:08,816][INFO] - 97步开始
[2019-07-17 18:00:09,389][INFO] - 98步开始
[2019-07-17 18:00:09,986][INFO] - 99步开始
[2019-07-17 18:00:13,165][INFO] - 截图保存到:/idea/UIAutoTest/pic/snap_1.xls_step99_2019-07-17 18:00:10.png
[2019-07-17 18:00:13,693][INFO] - 100步开始
[2019-07-17 18:00:14,197][INFO] - sleep:500毫秒
[2019-07-17 18:00:14,708][INFO] - 101步开始
[2019-07-17 18:00:15,356][INFO] - end步开始
[2019-07-17 18:00:15,356][INFO] - Sheet2执行完成
[2019-07-17 18:00:15,591][INFO] - 表格:Sheet2完成，关闭浏览器
[2019-07-17 18:00:15,690][INFO] - 1.xls执行完成
[2019-07-17 18:00:15,691][INFO] - =========脚本完成=========
[2019-07-17 18:00:45,477][INFO] - =========脚本启动=========
[2019-07-17 18:00:45,478][INFO] - 开始执行脚本：1.xls
[2019-07-17 18:00:45,772][INFO] - 启动chrome浏览器
[2019-07-17 18:00:48,673][INFO] - 1步开始
[2019-07-17 18:00:49,354][INFO] - 2步开始
[2019-07-17 18:01:19,406][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 18:01:19,507][ERROR] - 第2步发生异常
[2019-07-17 18:01:19,508][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:177)
	at Start.main(Start.java:8)
[2019-07-17 18:01:19,514][INFO] - 执行报错，关闭浏览器
[2019-07-17 18:01:19,515][INFO] - 1.xls执行完成
[2019-07-17 18:01:19,522][INFO] - 启动chrome浏览器
[2019-07-17 18:01:21,828][INFO] - 1步开始
[2019-07-17 18:01:22,510][INFO] - 2步开始
[2019-07-17 18:01:23,154][INFO] - 3步开始
[2019-07-17 18:01:28,253][INFO] - 4步开始
[2019-07-17 18:01:29,260][INFO] - 5步开始
[2019-07-17 18:01:30,063][INFO] - 6步开始
[2019-07-17 18:01:32,733][INFO] - 7步开始
[2019-07-17 18:01:33,345][INFO] - 8步开始
[2019-07-17 18:01:34,096][INFO] - 9步开始
[2019-07-17 18:01:34,656][INFO] - 94步开始
[2019-07-17 18:01:35,787][INFO] - 95步开始
[2019-07-17 18:01:36,426][INFO] - 96步开始
[2019-07-17 18:01:37,029][INFO] - 97步开始
[2019-07-17 18:01:37,594][INFO] - 98步开始
[2019-07-17 18:01:38,189][INFO] - 99步开始
[2019-07-17 18:01:41,168][INFO] - 截图保存到:/idea/UIAutoTest/pic/snap_1.xls_step99_2019-07-17 18:01:38.png
[2019-07-17 18:01:41,689][INFO] - 100步开始
[2019-07-17 18:01:42,190][INFO] - sleep:500毫秒
[2019-07-17 18:01:42,703][INFO] - 101步开始
[2019-07-17 18:01:43,304][INFO] - end步开始
[2019-07-17 18:01:43,305][INFO] - Sheet2执行完成
[2019-07-17 18:01:43,535][INFO] - 表格:Sheet2完成，关闭浏览器
[2019-07-17 18:01:43,535][INFO] - 1.xls执行完成
[2019-07-17 18:01:43,535][INFO] - =========脚本完成=========
[2019-07-17 18:47:49,871][INFO] - =========脚本启动=========
[2019-07-17 18:47:52,099][INFO] - 开始执行脚本：1.xls
[2019-07-17 18:47:52,354][INFO] - 启动chrome浏览器
[2019-07-17 18:47:55,311][INFO] - 1步开始
[2019-07-17 18:47:55,989][INFO] - 2步开始
[2019-07-17 18:47:57,093][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 18:47:57,134][ERROR] - 第2步发生异常
[2019-07-17 18:47:57,134][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:177)
	at Start.main(Start.java:8)
[2019-07-17 18:47:57,136][INFO] - 执行报错，关闭浏览器
[2019-07-17 18:47:57,328][INFO] - 1.xls执行完成
[2019-07-17 18:47:57,333][INFO] - 启动chrome浏览器
[2019-07-17 18:48:00,126][INFO] - 1步开始
[2019-07-17 18:48:00,828][INFO] - 2步开始
[2019-07-17 18:48:00,849][ERROR] - 元素(ID)'password'找不到
[2019-07-17 18:48:00,922][ERROR] - 第2步发生异常
[2019-07-17 18:48:00,922][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:177)
	at Start.main(Start.java:8)
[2019-07-17 18:48:00,926][INFO] - 执行报错，关闭浏览器
[2019-07-17 18:48:01,047][INFO] - 1.xls执行完成
[2019-07-17 18:48:01,047][INFO] - =========脚本完成=========
[2019-07-17 18:49:29,525][INFO] - =========脚本启动=========
[2019-07-17 18:49:31,816][INFO] - 开始执行脚本：1.xls
[2019-07-17 18:49:32,075][INFO] - 启动chrome浏览器
[2019-07-17 18:49:34,712][INFO] - 1步开始
[2019-07-17 18:49:35,395][INFO] - 2步开始
[2019-07-17 18:50:05,883][ERROR] - 元素(ID)'password1'找不到
[2019-07-17 18:50:05,992][ERROR] - 第2步发生异常
[2019-07-17 18:50:05,997][ERROR] - 
java.lang.NullPointerException
	at common.ElementAction.action(ElementAction.java:177)
	at Start.main(Start.java:8)
[2019-07-17 18:50:06,002][INFO] - 执行报错，关闭浏览器
[2019-07-17 18:50:06,165][INFO] - 1.xls执行完成
[2019-07-17 18:50:06,169][INFO] - 启动chrome浏览器
[2019-07-17 18:50:08,387][INFO] - 1步开始
[2019-07-17 18:50:09,077][INFO] - 2步开始
[2019-07-17 18:50:09,726][INFO] - 3步开始
[2019-07-17 18:50:11,200][INFO] - 4步开始
[2019-07-17 18:50:15,273][INFO] - 5步开始
[2019-07-17 18:50:16,084][INFO] - 6步开始
[2019-07-17 18:50:18,296][INFO] - 7步开始
[2019-07-17 18:50:18,993][INFO] - 8步开始
[2019-07-17 18:50:19,730][INFO] - 9步开始
[2019-07-17 18:50:20,302][INFO] - 94步开始
[2019-07-17 18:50:21,677][INFO] - 95步开始
[2019-07-17 18:50:22,359][INFO] - 96步开始
[2019-07-17 18:50:22,966][INFO] - 97步开始
[2019-07-17 18:50:23,539][INFO] - 98步开始
[2019-07-17 18:50:24,157][INFO] - 99步开始
[2019-07-17 18:50:27,255][INFO] - 截图保存到:/idea/UIAutoTest/pic/snap_1.xls_step99_2019-07-17 18:50:24.png
[2019-07-17 18:50:27,780][INFO] - 100步开始
[2019-07-17 18:50:28,284][INFO] - sleep:500毫秒
[2019-07-17 18:50:28,800][INFO] - 101步开始
[2019-07-17 18:50:29,412][INFO] - end步开始
[2019-07-17 18:50:29,412][INFO] - Sheet2执行完成
[2019-07-17 18:50:29,665][INFO] - 表格:Sheet2完成，关闭浏览器
[2019-07-17 18:50:29,747][INFO] - 1.xls执行完成
[2019-07-17 18:50:29,747][INFO] - =========脚本完成=========
[2019-07-17 18:52:59,070][INFO] - =========脚本启动=========
[2019-07-17 18:53:17,459][ERROR] - Communications link failure

The last packet successfully received from the server was 18,028 milliseconds ago.  The last packet sent successfully to the server was 18,028 milliseconds ago.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 18,028 milliseconds ago.  The last packet sent successfully to the server was 18,028 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1218)
	at util.DataBaseSource.getReportTableName(DataBaseSource.java:116)
	at common.ElementAction.action(ElementAction.java:83)
	at Start.main(Start.java:8)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 18,028 milliseconds ago.  The last packet sent successfully to the server was 18,028 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:562)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:732)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:671)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:986)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:921)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1154)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1186)
	... 3 more
Caused by: java.net.SocketException: Operation timed out (Read failed)
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.mysql.cj.protocol.ReadAheadInputStream.fill(ReadAheadInputStream.java:107)
	at com.mysql.cj.protocol.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:150)
	at com.mysql.cj.protocol.ReadAheadInputStream.read(ReadAheadInputStream.java:180)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:556)
	... 9 more
[2019-07-17 18:53:25,325][ERROR] - Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at util.DataBaseSource.getConn(DataBaseSource.java:31)
	at util.DataBaseSource.createReportTable(DataBaseSource.java:131)
	at common.ElementAction.action(ElementAction.java:84)
	at Start.main(Start.java:8)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
	... 9 more
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
	... 12 more
[2019-07-17 18:53:30,933][INFO] - =========脚本启动=========
[2019-07-17 18:53:39,035][ERROR] - Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at util.DataBaseSource.getConn(DataBaseSource.java:31)
	at util.DataBaseSource.getReportTableName(DataBaseSource.java:112)
	at common.ElementAction.action(ElementAction.java:83)
	at Start.main(Start.java:8)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
	... 9 more
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
	... 12 more
[2019-07-17 18:55:27,164][INFO] - =========脚本启动=========
[2019-07-17 18:55:35,367][ERROR] - Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at util.DataBaseSource.getConn(DataBaseSource.java:31)
	at util.DataBaseSource.getReportTableName(DataBaseSource.java:112)
	at common.ElementAction.action(ElementAction.java:83)
	at Start.main(Start.java:8)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
	... 9 more
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
	... 12 more
